"use client";

import * as React from "react";
import { Lightbulb, RefreshCw } from "lucide-react";
import { apiJson } from "@/lib/api/http";
import { track } from "@/lib/analytics/tracker";

interface InsightResponse {
  insights: string;
  provider: string;
  model: string;
  latencyMs: number;
}

const PROVIDER_LABEL: Record<string, string> = {
  groq: "Groq · Llama 3.3",
  gemini: "Google Gemini",
  deterministic: "Rules engine",
};

/** Minimal, safe markdown: bullets + **bold**. Rendered as React nodes (no innerHTML). */
function renderLine(line: string, i: number) {
  const text = line.replace(/^\s*[-*•]\s*/, "");
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  return (
    <li key={i} className="flex gap-2.5">
      <span aria-hidden className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-500" />
      <span>
        {parts.map((p, j) =>
          p.startsWith("**") ? (
            <strong key={j} className="font-semibold text-nexus-on-surface">
              {p.slice(2, -2)}
            </strong>
          ) : (
            <React.Fragment key={j}>{p}</React.Fragment>
          )
        )}
      </span>
    </li>
  );
}

export function AIInsightsPanel({ timeframe }: { timeframe: string }) {
  const [data, setData] = React.useState<InsightResponse | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState(false);

  const load = React.useCallback(async () => {
    setLoading(true);
    setError(false);
    try {
      const res = await apiJson<InsightResponse>("/api/v1/ai/insights", {
        method: "POST",
        body: JSON.stringify({ timeframe }),
      });
      setData(res);
      track("ai_query", { feature: "analytics_insights", provider: res.provider });
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }, [timeframe]);

  React.useEffect(() => {
    load();
  }, [load]);

  const lines = (data?.insights || "").split("\n").filter((l) => l.trim());

  return (
    <section aria-labelledby="ai-insights-title" className="tactile-card p-5" aria-busy={loading}>
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="h-9 w-9 rounded-lg bg-brand-50 dark:bg-nexus-secondary-container flex items-center justify-center">
            <Lightbulb className="h-[18px] w-[18px] text-brand-700 dark:text-nexus-on-secondary-container" aria-hidden />
          </div>
          <div>
            <h2 id="ai-insights-title" className="text-sm font-semibold text-nexus-on-surface">
              Key insights
            </h2>
            <p className="text-xs text-nexus-on-surface-variant">
              {data ? `Generated by ${PROVIDER_LABEL[data.provider] || data.provider}` : "Summarising your metrics"}
              {data && data.latencyMs > 0 ? ` · ${data.latencyMs} ms` : ""}
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={load}
          disabled={loading}
          className="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium text-nexus-on-surface-variant hover:bg-nexus-surface-container hover:text-nexus-on-surface disabled:opacity-50"
          aria-label="Regenerate insights"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} aria-hidden />
          Regenerate
        </button>
      </div>

      <div className="mt-4 text-sm text-nexus-on-surface-variant leading-relaxed">
        {loading && !data ? (
          <div className="space-y-2.5" aria-hidden>
            {[92, 80, 86].map((w) => (
              <div key={w} className="h-3.5 rounded bg-nexus-surface-container animate-pulse" style={{ width: `${w}%` }} />
            ))}
          </div>
        ) : error ? (
          <p role="alert">Insights are unavailable right now. Try again in a moment.</p>
        ) : (
          <ul className="space-y-2">{lines.map(renderLine)}</ul>
        )}
      </div>
    </section>
  );
}
