"""add_erd_relationships

Revision ID: aad5e71dd967
Revises: 001_initial_schema
Create Date: 2026-09-07 22:45:27.005955

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aad5e71dd967'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS "DataPipelineHealth", "Notification", "OperationalEvent", "Decision", "IncidentTimeline", "Simulation", "Incident", "Order", "Route", "Vehicle", "Warehouse", "User", "AuditLog", "Workspace" CASCADE;')
    op.create_index(op.f('ix_ai_insights_workspace_id'), 'ai_insights', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'ai_insights', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('avatar_preferences_user_id_key'), 'avatar_preferences', type_='unique')
    op.create_index(op.f('ix_avatar_preferences_user_id'), 'avatar_preferences', ['user_id'], unique=True)
    op.create_foreign_key(None, 'avatar_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_decisions_incident_id'), 'decisions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_decisions_simulation_id'), 'decisions', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_decisions_workspace_id'), 'decisions', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'decisions', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'decisions', 'incidents', ['incident_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'decisions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_event_outbox_workspace_id'), 'event_outbox', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'event_outbox', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_workspace_id'), 'feedback', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'feedback', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_incident_timelines_incident_id'), 'incident_timelines', ['incident_id'], unique=False)
    op.drop_constraint(op.f('incident_timelines_incident_id_fkey'), 'incident_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'incident_timelines', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.add_column('incidents', sa.Column('vehicle_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_incidents_vehicle_id'), 'incidents', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_incidents_workspace_id'), 'incidents', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('incidents_workspace_id_fkey'), 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'incidents', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('integrations_provider_key'), 'integrations', type_='unique')
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=True)
    op.drop_constraint(op.f('invitations_token_key'), 'invitations', type_='unique')
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'invitations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_operational_events_workspace_id'), 'operational_events', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'operational_events', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('warehouse_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('route_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_route_id'), 'orders', ['route_id'], unique=False)
    op.create_index(op.f('ix_orders_vehicle_id'), 'orders', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_orders_warehouse_id'), 'orders', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_orders_workspace_id'), 'orders', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('orders_vehicle_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_workspace_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'routes', ['route_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_pipeline_health_source_name'), 'pipeline_health', ['source_name'], unique=True)
    op.create_index(op.f('ix_reports_workspace_id'), 'reports', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_routes_dest_warehouse_id'), 'routes', ['dest_warehouse_id'], unique=False)
    op.create_index(op.f('ix_routes_origin_warehouse_id'), 'routes', ['origin_warehouse_id'], unique=False)
    op.create_index(op.f('ix_routes_workspace_id'), 'routes', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('routes_workspace_id_fkey'), 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'routes', 'warehouses', ['origin_warehouse_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'routes', 'warehouses', ['dest_warehouse_id'], ['id'], ondelete='CASCADE')
    op.add_column('simulations', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_simulations_incident_id'), 'simulations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_simulations_user_id'), 'simulations', ['user_id'], unique=False)
    op.create_index(op.f('ix_simulations_workspace_id'), 'simulations', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('simulations_workspace_id_fkey'), 'simulations', type_='foreignkey')
    op.create_foreign_key(None, 'simulations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'simulations', 'incidents', ['incident_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'simulations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('users_workspace_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_vehicles_current_route_id'), 'vehicles', ['current_route_id'], unique=False)
    op.create_index(op.f('ix_vehicles_workspace_id'), 'vehicles', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('vehicles_current_route_id_fkey'), 'vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicles_workspace_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'routes', ['current_route_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'vehicles', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_warehouses_workspace_id'), 'warehouses', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('warehouses_workspace_id_fkey'), 'warehouses', type_='foreignkey')
    op.create_foreign_key(None, 'warehouses', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_workspace_memberships_user_id'), 'workspace_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('workspace_memberships_workspace_id_fkey'), 'workspace_memberships', type_='foreignkey')
    op.drop_constraint(op.f('workspace_memberships_user_id_fkey'), 'workspace_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_memberships', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_memberships', type_='foreignkey')
    op.drop_constraint(None, 'workspace_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_memberships_user_id_fkey'), 'workspace_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workspace_memberships_workspace_id_fkey'), 'workspace_memberships', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_user_id'), table_name='workspace_memberships')
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_foreign_key(op.f('warehouses_workspace_id_fkey'), 'warehouses', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_warehouses_workspace_id'), table_name='warehouses')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_workspace_id_fkey'), 'vehicles', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('vehicles_current_route_id_fkey'), 'vehicles', 'routes', ['current_route_id'], ['id'])
    op.drop_index(op.f('ix_vehicles_workspace_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_current_route_id'), table_name='vehicles')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_workspace_id_fkey'), 'users', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.create_foreign_key(op.f('simulations_workspace_id_fkey'), 'simulations', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_simulations_workspace_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_user_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_incident_id'), table_name='simulations')
    op.drop_column('simulations', 'user_id')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('routes_workspace_id_fkey'), 'routes', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_routes_workspace_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_origin_warehouse_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_dest_warehouse_id'), table_name='routes')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_workspace_id'), table_name='reports')
    op.drop_index(op.f('ix_pipeline_health_source_name'), table_name='pipeline_health')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_workspace_id_fkey'), 'orders', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('orders_vehicle_id_fkey'), 'orders', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_index(op.f('ix_orders_workspace_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_warehouse_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_vehicle_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_route_id'), table_name='orders')
    op.drop_column('orders', 'route_id')
    op.drop_column('orders', 'warehouse_id')
    op.drop_constraint(None, 'operational_events', type_='foreignkey')
    op.drop_index(op.f('ix_operational_events_workspace_id'), table_name='operational_events')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.create_unique_constraint(op.f('invitations_token_key'), 'invitations', ['token'])
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.create_unique_constraint(op.f('integrations_provider_key'), 'integrations', ['provider'])
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key(op.f('incidents_workspace_id_fkey'), 'incidents', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_incidents_workspace_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_vehicle_id'), table_name='incidents')
    op.drop_column('incidents', 'vehicle_id')
    op.drop_constraint(None, 'incident_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('incident_timelines_incident_id_fkey'), 'incident_timelines', 'incidents', ['incident_id'], ['id'])
    op.drop_index(op.f('ix_incident_timelines_incident_id'), table_name='incident_timelines')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_workspace_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_constraint(None, 'event_outbox', type_='foreignkey')
    op.drop_index(op.f('ix_event_outbox_workspace_id'), table_name='event_outbox')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_index(op.f('ix_decisions_workspace_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_simulation_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_incident_id'), table_name='decisions')
    op.drop_constraint(None, 'avatar_preferences', type_='foreignkey')
    op.drop_index(op.f('ix_avatar_preferences_user_id'), table_name='avatar_preferences')
    op.create_unique_constraint(op.f('avatar_preferences_user_id_key'), 'avatar_preferences', ['user_id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(None, 'ai_insights', type_='foreignkey')
    op.drop_index(op.f('ix_ai_insights_workspace_id'), table_name='ai_insights')
    op.create_table('Incident',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='IncidentSeverity'), server_default=sa.text('\'HIGH\'::"IncidentSeverity"'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DETECTED', 'ACKNOWLEDGED', 'INVESTIGATING', 'SIMULATING', 'ACTION_PENDING', 'ACTION_APPLIED', 'RESOLVED', 'ARCHIVED', name='IncidentStatus'), server_default=sa.text('\'DETECTED\'::"IncidentStatus"'), autoincrement=False, nullable=False),
    sa.Column('affectedEntityType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('affectedEntityId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('affectedEntityName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rootCause', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aiAnalysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('potentialImpact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('costEstimate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4200.00'), autoincrement=False, nullable=False),
    sa.Column('ordersAffected', sa.INTEGER(), server_default=sa.text('14'), autoincrement=False, nullable=False),
    sa.Column('delayMinutes', sa.INTEGER(), server_default=sa.text('85'), autoincrement=False, nullable=False),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name='Incident_workspaceId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Incident_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Incident_code_key'), 'Incident', ['code'], unique=True)
    op.create_table('AuditLog',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actorId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actorName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('beforeJson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('afterJson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.TEXT(), server_default=sa.text("'127.0.0.1'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actorId'], ['User.id'], name=op.f('AuditLog_actorId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('AuditLog_pkey'))
    )
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMINISTRATOR', 'OPERATIONS_MANAGER', 'ANALYST', 'OPERATOR', 'VIEWER', name='Role'), server_default=sa.text('\'OPERATIONS_MANAGER\'::"Role"'), autoincrement=False, nullable=False),
    sa.Column('avatarUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('lastActive', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name='User_workspaceId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.create_table('Warehouse',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacityUnits', sa.INTEGER(), server_default=sa.text('10000'), autoincrement=False, nullable=False),
    sa.Column('currentUnits', sa.INTEGER(), server_default=sa.text('6200'), autoincrement=False, nullable=False),
    sa.Column('dockCount', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False),
    sa.Column('activeDocks', sa.INTEGER(), server_default=sa.text('8'), autoincrement=False, nullable=False),
    sa.Column('efficiencyPct', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('94.2'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'OPERATIONAL'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name='Warehouse_workspaceId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Warehouse_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Warehouse_code_key'), 'Warehouse', ['code'], unique=True)
    op.create_table('Vehicle',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), server_default=sa.text("'Freightliner eCascadia'::text"), autoincrement=False, nullable=False),
    sa.Column('driverName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('driverPhone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('capacityKg', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('18000'), autoincrement=False, nullable=False),
    sa.Column('currentLoadKg', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('11400'), autoincrement=False, nullable=False),
    sa.Column('batteryPct', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('82.0'), autoincrement=False, nullable=False),
    sa.Column('healthScore', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('98.5'), autoincrement=False, nullable=False),
    sa.Column('speedKmh', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('65.0'), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('heading', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('90.0'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('IDLE', 'IN_TRANSIT', 'LOADING', 'MAINTENANCE', 'OUT_OF_SERVICE', name='VehicleStatus'), server_default=sa.text('\'IN_TRANSIT\'::"VehicleStatus"'), autoincrement=False, nullable=False),
    sa.Column('currentRouteId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['currentRouteId'], ['Route.id'], name='Vehicle_currentRouteId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name='Vehicle_workspaceId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Vehicle_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Vehicle_code_key'), 'Vehicle', ['code'], unique=True)
    op.create_table('IncidentTimeline',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('incidentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DETECTED', 'ACKNOWLEDGED', 'INVESTIGATING', 'SIMULATING', 'ACTION_PENDING', 'ACTION_APPLIED', 'RESOLVED', 'ARCHIVED', name='IncidentStatus'), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actorName', sa.TEXT(), server_default=sa.text("'Nexus Automated Telemetry'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incidentId'], ['Incident.id'], name=op.f('IncidentTimeline_incidentId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('IncidentTimeline_pkey'))
    )
    op.create_table('Route',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('originWarehouseId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('destWarehouseId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('distanceKm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avgDurationMins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('riskScore', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('12.0'), autoincrement=False, nullable=False),
    sa.Column('trafficCondition', sa.TEXT(), server_default=sa.text("'CLEAR'::text"), autoincrement=False, nullable=False),
    sa.Column('waypointsJson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['destWarehouseId'], ['Warehouse.id'], name='Route_destWarehouseId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originWarehouseId'], ['Warehouse.id'], name='Route_originWarehouseId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name='Route_workspaceId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Route_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Route_code_key'), 'Route', ['code'], unique=True)
    op.create_table('Simulation',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incidentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'RUNNING', 'COMPLETED', 'APPLIED', 'FAILED', name='SimulationStatus'), server_default=sa.text('\'COMPLETED\'::"SimulationStatus"'), autoincrement=False, nullable=False),
    sa.Column('variablesJson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('baselineMetrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('simulatedMetrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('aiBriefing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('appliedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('appliedBy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incidentId'], ['Incident.id'], name=op.f('Simulation_incidentId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Simulation_userId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name=op.f('Simulation_workspaceId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Simulation_pkey'))
    )
    op.create_index(op.f('Simulation_code_key'), 'Simulation', ['code'], unique=True)
    op.create_table('Order',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('orderNumber', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('customerName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='OrderPriority'), server_default=sa.text('\'NORMAL\'::"OrderPriority"'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELLED', name='OrderStatus'), server_default=sa.text('\'IN_TRANSIT\'::"OrderStatus"'), autoincrement=False, nullable=False),
    sa.Column('warehouseId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('routeId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vehicleId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('estimatedEta', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('itemsCount', sa.INTEGER(), server_default=sa.text('45'), autoincrement=False, nullable=False),
    sa.Column('totalCost', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1250.00'), autoincrement=False, nullable=False),
    sa.Column('slaCompliant', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], name=op.f('Order_routeId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicleId'], ['Vehicle.id'], name=op.f('Order_vehicleId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouseId'], ['Warehouse.id'], name=op.f('Order_warehouseId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name=op.f('Order_workspaceId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Order_pkey'))
    )
    op.create_index(op.f('Order_orderNumber_key'), 'Order', ['orderNumber'], unique=True)
    op.create_table('Workspace',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('region', sa.TEXT(), server_default=sa.text("'North America Central'::text"), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Workspace_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Workspace_code_key'), 'Workspace', ['code'], unique=True)
    op.create_table('OperationalEvent',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workspaceId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('eventType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), server_default=sa.text("'INFO'::text"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payloadJson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurredAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], name=op.f('OperationalEvent_workspaceId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('OperationalEvent_pkey'))
    )
    op.create_table('Notification',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'INFO'::text"), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entityId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deepLink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Notification_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Notification_pkey'))
    )
    op.create_table('DataPipelineHealth',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sourceName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sourceType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'HEALTHY'::text"), autoincrement=False, nullable=False),
    sa.Column('latencyMs', sa.INTEGER(), server_default=sa.text('18'), autoincrement=False, nullable=False),
    sa.Column('throughputPerSec', sa.INTEGER(), server_default=sa.text('2400'), autoincrement=False, nullable=False),
    sa.Column('recordsToday', sa.INTEGER(), server_default=sa.text('1840000'), autoincrement=False, nullable=False),
    sa.Column('errorCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lastSyncAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('DataPipelineHealth_pkey'))
    )
    op.create_index(op.f('DataPipelineHealth_sourceName_key'), 'DataPipelineHealth', ['sourceName'], unique=True)
    # ### end Alembic commands ###
