"use client";

import * as React from "react";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Sparkles, Printer, CheckCircle2, ArrowRight } from "lucide-react";
import { formatDateTime } from "@/lib/utils";
import { useToast } from "@/components/ui/toast";
import { FadeIn, StaggerContainer, StaggerItem, TactileCard } from "@/components/ui/motion-animations";

export default function ReportsPage() {
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [reportsList, setReportsList] = React.useState([
    {
      id: "rep-1",
      title: "Daily Operations Executive Briefing · North America",
      date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      type: "EXECUTIVE_BRIEF",
      summary: "80% fleet utilization with 96.8% SLA adherence. 1 critical snowstorm reroute evaluated and applied via simulation SIM-901.",
      author: "NEXUS Groq AI Engine",
    },
    {
      id: "rep-2",
      title: "Incident INC-8041 Post-Mortem & Decision Impact",
      date: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      type: "INCIDENT_AUDIT",
      summary: "Evaluated I-70 detour vs holding pattern. Decision applied transactionally: saved 135 minutes on high-value AeroTech shipment.",
      author: "Sarah Chen (Ops Manager)",
    },
    {
      id: "rep-3",
      title: "Weekly Cold-Chain Fleet Thermal Performance Audit",
      date: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
      type: "FLEET_AUDIT",
      summary: "Biopharma transport integrity maintained at 99.8% compliance across Volvo VNR cryogenic units.",
      author: "Elena Rostova",
    },
  ]);

  const handleGenerateNewReport = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch("/api/v1/ai/briefing", { method: "POST" });
      const data = await res.json();
      const newReport = {
        id: `rep-${Date.now()}`,
        title: `Operations Command Synthesis · ${new Date().toLocaleDateString()}`,
        date: new Date().toISOString(),
        type: "EXECUTIVE_BRIEF",
        summary: data.briefing || "Real-time fleet operations report synthesized from active IoT telemetry and simulation predictions.",
        author: "NEXUS AI Intelligence",
      };

      setReportsList((prev) => [newReport, ...prev]);

      toast({
        title: "Executive Report Compiled",
        message: "Generated executive intelligence report from active telemetry.",
        type: "ai",
      });
    } catch {
      toast({
        title: "Executive Report Compiled",
        message: "Generated deterministic operational report.",
        type: "info",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadReport = (rep: typeof reportsList[0]) => {
    const markdownContent = `# ${rep.title}\n\n**Date:** ${new Date(rep.date).toLocaleString()}\n**Classification:** ${rep.type}\n**Author:** ${rep.author}\n\n## Executive Summary\n${rep.summary}\n\n---\n*Generated by NEXUS Autonomous Operations Intelligence Platform*`;
    const blob = new Blob([markdownContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rep.id}-${rep.type.toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Exported",
      message: `Downloaded ${rep.id} dossier.`,
      type: "success",
    });
  };

  return (
    <AppShell>
      <FadeIn className="space-y-6 max-w-5xl mx-auto">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-mono-data text-nexus-on-surface-variant uppercase">
              <span>Executive Briefing Center</span>
              <span>·</span>
              <span>Auditable Operational Reports</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-nexus-on-surface tracking-tight mt-1">
              Command Briefings & Reports
            </h1>
          </div>

          <div className="flex items-center gap-3">
            <Button
              variant="simulation"
              size="sm"
              onClick={handleGenerateNewReport}
              isLoading={isGenerating}
              className="font-mono-data text-xs shadow-tactile"
            >
              <Sparkles className="h-3.5 w-3.5 mr-1.5" />
              Compile Live Executive Briefing
            </Button>
          </div>
        </div>

        {/* Reports List */}
        <StaggerContainer className="space-y-4">
          {reportsList.map((rep) => (
            <StaggerItem key={rep.id}>
              <TactileCard>
                <Card>
                  <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                    <div className="flex items-start gap-4">
                      <div className="p-3 rounded-xl bg-nexus-surface-container text-nexus-secondary shrink-0 mt-1">
                        <FileText className="h-5 w-5" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <Badge variant="healthy" size="sm">
                            {rep.type}
                          </Badge>
                          <span className="text-xs text-nexus-on-surface-variant font-mono-data">
                            {formatDateTime(rep.date)}
                          </span>
                        </div>
                        <h3 className="text-base font-bold text-nexus-on-surface mt-1">{rep.title}</h3>
                        <p className="text-xs text-nexus-on-surface-variant mt-1 max-w-2xl leading-relaxed">
                          {rep.summary}
                        </p>
                        <p className="text-[11px] font-mono-data text-nexus-on-surface-variant/80 mt-2">
                          Compiled by: {rep.author}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => handleDownloadReport(rep)}
                        className="text-xs font-mono-data"
                      >
                        <Download className="h-3.5 w-3.5 mr-1" />
                        Export
                      </Button>
                    </div>
                  </div>
                </Card>
              </TactileCard>
            </StaggerItem>
          ))}
        </StaggerContainer>
      </FadeIn>
    </AppShell>
  );
}

