export type RoleType =
  | "ADMINISTRATOR"
  | "OPERATIONS_MANAGER"
  | "ANALYST"
  | "OPERATOR"
  | "VIEWER";

export const PERMISSIONS = {
  VIEW_OPERATIONS: ["ADMINISTRATOR", "OPERATIONS_MANAGER", "ANALYST", "OPERATOR", "VIEWER"],
  EDIT_OPERATIONS: ["ADMINISTRATOR", "OPERATIONS_MANAGER", "OPERATOR"],
  RUN_SIMULATION: ["ADMINISTRATOR", "OPERATIONS_MANAGER", "ANALYST"],
  APPLY_DECISION: ["ADMINISTRATOR", "OPERATIONS_MANAGER"],
  RESOLVE_INCIDENT: ["ADMINISTRATOR", "OPERATIONS_MANAGER", "OPERATOR"],
  VIEW_ANALYTICS: ["ADMINISTRATOR", "OPERATIONS_MANAGER", "ANALYST", "OPERATOR", "VIEWER"],
  VIEW_INTELLIGENCE: ["ADMINISTRATOR", "OPERATIONS_MANAGER", "ANALYST"],
  MANAGE_USERS: ["ADMINISTRATOR"],
  MANAGE_INTEGRATIONS: ["ADMINISTRATOR"],
  VIEW_AUDIT_LOGS: ["ADMINISTRATOR", "OPERATIONS_MANAGER"],
  SYSTEM_HEALTH: ["ADMINISTRATOR", "OPERATIONS_MANAGER"],
} as const;

export function hasPermission(role: RoleType | string, permission: keyof typeof PERMISSIONS): boolean {
  const allowedRoles = PERMISSIONS[permission] as readonly string[];
  return allowedRoles.includes(role);
}
